// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3DgHJkBWh0IW0liguH6DkhZvtcxaJXME',
    appId: '1:668033377863:web:b68861ca1833599d767362',
    messagingSenderId: '668033377863',
    projectId: 'rideshare-app-485711',
    authDomain: 'rideshare-app-485711.firebaseapp.com',
    storageBucket: 'rideshare-app-485711.firebasestorage.app',
    measurementId: 'G-841PGBRPQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzTJd5aryzASJNm-QEL7lEf7APl0hJpdk',
    appId: '1:668033377863:android:7a28df11946b0710767362',
    messagingSenderId: '668033377863',
    projectId: 'rideshare-app-485711',
    storageBucket: 'rideshare-app-485711.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDawUK9eQOO9YI6QSWllw9fb3SoS6GCGUU',
    appId: '1:668033377863:ios:d1ec7d04cfe83375767362',
    messagingSenderId: '668033377863',
    projectId: 'rideshare-app-485711',
    storageBucket: 'rideshare-app-485711.firebasestorage.app',
    iosBundleId: 'com.example.rideshareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDawUK9eQOO9YI6QSWllw9fb3SoS6GCGUU',
    appId: '1:668033377863:ios:d1ec7d04cfe83375767362',
    messagingSenderId: '668033377863',
    projectId: 'rideshare-app-485711',
    storageBucket: 'rideshare-app-485711.firebasestorage.app',
    iosBundleId: 'com.example.rideshareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3DgHJkBWh0IW0liguH6DkhZvtcxaJXME',
    appId: '1:668033377863:web:6943e410973b7687767362',
    messagingSenderId: '668033377863',
    projectId: 'rideshare-app-485711',
    authDomain: 'rideshare-app-485711.firebaseapp.com',
    storageBucket: 'rideshare-app-485711.firebasestorage.app',
    measurementId: 'G-9MTGHF9TL2',
  );
}
